### ISSUE TITLE
Notificação de lembretes

### ISSUE THREAD

**Issue by CristianoNunes** [roldaojr/BescheLab#26]
Aparecer notificações ao se logar no sistema, notificação que há pagamentos que se vencem naquele dia.

**Comment by wandertorres** [comment]
Poderia usar o ícone de notificação que já tinha do template. Acho que notificaria só pagamentos já em atraso e exames que passaram da data e não foram feitos.

**Comment by roldaojr** [comment]
Melhor colocar um painel na tela principal, pois é desnecessário colocar pra aparecer em todas as telas

**Comment by roldaojr** [comment]
Poderia colocar notificações de pagamento pendentes e exames do dia

**Comment by wandertorres** [comment]
É, pode ser um painel também. Agora notificar exames do dia... a agenda já não mostra isso?
