### ISSUE TITLE
Alteração Fluxo de Caixa

### ISSUE THREAD

**Issue by CristianoNunes** [roldaojr/BescheLab#30]
1- Setar no fluxo de caixa pela data de pagamento e não de vencimento.
2- Campos para exibir na lista do Fluxo de Caixa: Tipo de Lançamento, Nome,  Valor, Data do Pagamento.
3- Acrescentar campo SALDO, onde o valor desse campo é as ENTRADAS menos as DESPESAS.

**Comment by wandertorres** [comment]
As entradas menos as saídas do período selecionado.

Esse campo pode ficar abaixo da tabela, numa div separada por uma linha e alinhado a direita.
