### ISSUE TITLE
Ajustar marcação de exame

### ISSUE THREAD

**Issue by wandertorres** [roldaojr/BescheLab#31]
Ao marcar um exame, quando vai para a tela de adicionar lançamento, se o usuário sair para outra tela sem sem salvar. a marcação é salva, mas o lançamento não.

**Comment by roldaojr** [comment]
E como deveria ser?

**Comment by wandertorres** [comment]
Não sei qual seria a melhor opção, mas poderia por exemplo a marcação só ser salva no banco depois de todo o processo concluído.

**Comment by wandertorres** [comment]
Da forma que está agora pode ser feito a marcação de um exame e não ser adicionado lançamento. Então essa marcação não seria paga.
